#!/bin/bash
set -e

if [[ "$(id -u)" -ne 0 ]]; then
    echo 'Must be run as root.'
    exit 1
fi

# Get the parent directory of the script
script_dir="$(dirname "$(readlink -f "$0")")"

# Build packages using all available cores
cores="$(grep -c ^processor /proc/cpuinfo)"
if [[ "$cores" =~ ^[0-9]+$ ]]; then
    sed -i "s/^#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$((cores + 1))\"/" /etc/makepkg.conf
    sed -i "s/^COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $cores -z -)/" /etc/makepkg.conf
fi

# Update the system and populate the mirror list
pacman -Syyu --noconfirm
pacman -S --noconfirm --needed reflector
reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist

# Install the AUR helper yay
pacman -S --noconfirm --needed git base-devel
buildDir="$(runuser -u nobody -- mktemp -d)"
cd "$buildDir"
runuser -u nobody -- git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
runuser -u nobody -- makepkg -s
pacman --noconfirm --needed -U -- *.pkg.tar.*

# Install regular packages
pacman -S --noconfirm --needed - < "$script_dir/pkgs"
pacman -S --noconfirm --needed --asdeps - < "$script_dir/opt-pkgs"

installAur() {
    pkg="$1"
    if pacman -Q "$pkg" &>/dev/null; then
        cd "$buildDir"
        runuser -u nobody -- yay -G "$pkg"
        cd "$pkg"
        runuser -u nobody -- makepkg -s
        pacman -U --noconfirm -- *.pkg.tar.*
        cd "$buildDir"
        rm -r "$pkg"
    fi
}

# Install AUR packages
while read -r pkg; do
    installAur "$pkg"
done < "$script_dir/aur-pkgs"

while read -r pkg; do
    installAur "$pkg"
    pacman -D --asdeps "$pkg"
done < "$script_dir/aur-opt-pkgs"

cd "$script_dir"
rm -r "$buildDir"

# Remove build dependencies
pacman -Qqtd | pacman -Rns -

# Install system configuration files
cp "$script_dir/etc/"* /etc

# Edit system configuration files

# Enable bluetooth automatically
sed -i 's/'#AutoEnable=false'/'AutoEnable=true'/g' /etc/bluetooth/main.conf

# Causes the presence of /etc/hushlogins to supress the tty login message
sed -i 's/^HUSHLOGIN/#HUSHLOGIN/' /etc/login.defs

# Supress fsck messages during boot
sed -i '/^HOOKS=/s/udev/systemd/' /etc/mkinitcpio.conf
mkinitcpio -p linux

# Needed for autorandr
udevadm control --reload-rules

# Start desktop environment by default
systemctl set-default graphical.target

# Enable and start services
systemctl enable --now NetworkManager.service
systemctl enable --now bluetooth.service
systemctl enable --now org.cups.cupsd.service
systemctl enable --now tlp.service
systemctl enable --now tlp-sleep.service
systemctl enable --now systemd-timesyncd.service
systemctl enable --now autorandr.service
systemctl daemon-reload
