#!/bin/bash
set -e

if [[ "$(id -u)" -ne 0 ]]; then
    echo 'Must be run as root.'
    exit 1
fi

# Get the parent directory of the script
script_dir="$(dirname "$(readlink -f "$0")")"

# Build packages using all available cores
cores="$(grep -c ^processor /proc/cpuinfo)"
if [[ "$cores" =~ ^[0-9]+$ ]]; then
    sed -i "s/^#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$((cores + 1))\"/" /etc/makepkg.conf
    sed -i "s/^COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $cores -z -)/" /etc/makepkg.conf
fi

# Update the system and populate the mirror list
pacman -Syyu --noconfirm
pacman -S --needed reflector
reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist

# Install the AUR helper yay
tmpDir="$(mktemp -d)"
cd "$tmpDir"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd "$script_dir"
rm -r "$tmpDir"

# Install packages
yay -S --no-confirm --needed - < "$script_dir/pkgs"
yay -S --no-confirm --needed - < "$script_dir/aur-pkgs"
yay -S --no-confirm --asdeps - < "$script_dir/opt-pkgs"

# Install system configuration files
cp "$script_dir/etc/"* /etc

# Edit system configuration files

# Enable bluetooth automatically
sed -i 's/'#AutoEnable=false'/'AutoEnable=true'/g' /etc/bluetooth/main.conf

# Causes the presence of /etc/hushlogins to supress the tty login message
sed -i 's/^HUSHLOGIN/#HUSHLOGIN/' /etc/login.defs

# Supress fsck messages during boot
sed -i '/^HOOKS=/s/udev/systemd/' /etc/mkinitcpio.conf
mkinitcpio -p linux

# Needed for autorandr
udevadm control --reload-rules

# Start desktop environment by default
systemctl set-default graphical.target

# Enable and start services
systemctl enable --now NetworkManager.service
systemctl enable --now bluetooth.service
systemctl enable --now tlp.service
systemctl enable --now tlp-sleep.service
systemctl enable --now systemd-timesyncd.service
systemctl enable --now autorandr.service
systemctl daemon-reload
